#!/usr/bin/env python3
"""
Amber – CasADi-backed inverse kinematics sanity-check
-----------------------------------------------------
*   Calculates joint angles from desired foot positions & COM (IK).
*   Runs forward kinematics with those angles.
*   Prints target vs. achieved positions and error for each foot.
"""

import numpy as np
import casadi as ca
import pinocchio as pin

# ----------------------------------------------------------------------
# Paths & constants
# ----------------------------------------------------------------------
URDF = "Amber/amber_free.urdf"            # path to your Amber URDF
CASADI_FN = "amber_reference_step.casadi"  # generated by amber_casadi_gen.py
FOOT_FRAMES = ["left_toe", "right_toe"]  # frame names in the URDF

# ----------------------------------------------------------------------
# Load CasADi IK function
# ----------------------------------------------------------------------
print(f"[INFO] Loading CasADi IK function from '{CASADI_FN}'...")
IK = ca.Function.load(CASADI_FN)

# ----------------------------------------------------------------------
# Numeric Pinocchio model for FK
# ----------------------------------------------------------------------
print("Pinocchio version:", pin.__version__)
model = pin.buildModelFromUrdf(URDF)
data = model.createData()
frame_ids = [model.getFrameId(name) for name in FOOT_FRAMES]

# ----------------------------------------------------------------------
# Initial guess for 4 actuated joints
# ----------------------------------------------------------------------
q_init = pin.neutral(model)
q_init[0]=12*3.14/180
print(f"[INFO] Initial guess joint vector (size {q_init.shape[0]}):", q_init)

# ----------------------------------------------------------------------
# Example test input: foot-world positions & center-of-mass
# ----------------------------------------------------------------------
# Format: [Lx, Rx, Ly, Ry, Lz, Rz] as used in amber_casadi_gen
foot_w = np.array([
    -3.77379e-08,  # Lx
    -2.98198e-08,  # Rx
    -0.0968508,    # Ly
     0.100716,     # Ry
     0.03,         # Lz
     0.43          # Rz
])
com_x, com_y, com_z = (
    3.552713678800501e-15,
    5.05611404187088e-24,
    1.363213682174683
)
com_x   = 0.0980#3.552713678800501e-15
com_y   = 0#5.05611404187088e-24
com_z   = 1.3711
phase = 0.0  # phase scalar (unused here, but required by function signature)

# ----------------------------------------------------------------------
# Run IK
print("----------------------------------------------------------------------")
print("[INFO] Running IK...")
res = IK(phase, foot_w, com_x, com_y, com_z, q_init)
q_ref = np.array(res[0]).flatten()
foot_body_flat = np.array(res[1]).flatten()
print("-----------[RESULT] IK joint angles [rad]:", q_ref,"--------------")

# ----------------------------------------------------------------------
# Forward kinematics to recover foot positions
# ----------------------------------------------------------------------
pin.forwardKinematics(model, data, q_ref)
pin.updateFramePlacements(model, data)
achieved = np.hstack([data.oMf[fid].translation for fid in frame_ids])
print("[INFO] Target foot-body positions (flattened):", foot_body_flat)
print("[INFO] Achieved foot positions (body frame):     ", achieved)

# ----------------------------------------------------------------------
# Compute and print errors
# ----------------------------------------------------------------------
targets = foot_body_flat.reshape(2, 3)
achieved_pts = achieved.reshape(2, 3)
errors = np.linalg.norm(targets - achieved_pts, axis=1)
for i, name in enumerate(FOOT_FRAMES):
    print(f" Foot '{name}': target {targets[i]} -> achieved {achieved_pts[i]} | err = {errors[i]:.3e} m")
print(f"[SUMMARY] Max position error = {errors.max():.3e} m, Avg = {errors.mean():.3e} m")
